version: 0.2

phases: 
    install:
        runtime-versions:
            dotnet: 5.0
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - dotnet build ./PlanHub.sln
    post_build:
        commands:
            - echo "we are in the post build phase"
            
